[package]
name = "factory"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
secp256k1 = {version = '0.31.1' ,features=["rand", "hashes"]}


[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
